version: '3.2'

services:
   tomcat:
     image: dtr.dts.utah.gov/mluce/tomcat:latest
     labels:
       - elcid=HL1231
       - devName=Matt Luce
       - devPhone=(801) 538-6058
       - devMail=mluce@utah.gov
       - campus=D
       - lifecycle=AT
       - stackyaml=https://git.dts.utah.gov/000193802/docker/tree/master/compose_files/CampusD-DTS-Hosting-AT-Sample.yml
       - artifact=campusD/Tomcat
       - com.docker.ucp.access.label=/Campus D/DTS/AT
       - com.docker.ucp.collection=/Campus D/DTS/AT
#     volumes:
#       - type: volume
#         source: nfs-tomcat
#         target: /nfsmount
#         volume:
#           nocopy: true
     ports:
       - target: 8080
         published: 30806
         protocol: tcp
         mode: ingress
     networks:
       app-internal:
         aliases:
           - appserver
     deploy:
        replicas: 2
        resources:
          limits:
            cpus: '1.00'
            memory: 1G
        restart_policy:
          condition: any
          delay: 60s
#          max_attempts: 3
          window: 120s
     environment:
        lifecycle: AT
        REPOURL: https://ci.dts.utah.gov/artifactory
        GROUP: campusD/Tomcat
        ARTIFACT: mluce_sample
        APIKEY: /run/secrets/api_key
     secrets:
       - source: CampusD_mluce_api_key
         target: api_key
#     logging:
#       driver: gelf
#       options:
#         gelf-address: "udp://eslindex8.utah.utad.state.ut.us:12203"
#         tag: "CampusD-DTS-Hosting-AT-Sample"
#volumes:
#   nfs-tomcat:
#      driver: local
#      driver_opts:
#        type: nfs
#        o: addr=168.180.133.124,rw
#        device: ":/docker/campusD/Tomcat"
networks:
       app-internal:
secrets:
       CampusD_mluce_api_key:
         external: true
